### ISSUE TITLE
你好大佬！请问ASRock B460M/ac-itx支持吗

### ISSUE THREAD

**Issue by Gollum916** [yrambler2001/Hackintosh-Intel-i5-10600-iGPU-AsRock-B460M-Pro4#3] opened 2020-08-16 01:56 UTC
ASRock B460M/ac-itx

**Comment by yrambler2001** [comment] 2020-08-16 09:37
Closed as duplicate of #4. Please use English.

**Closed as completed by yrambler2001** 2020-08-16 09:37 UTC
